### ISSUE TITLE
x-ratelimit limiter

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [jmcarp/requests-middleware#3]
api sites like github serve x-rate-limit headers - it would be nice to have a rate limiter that supports those

**Comment by jmcarp** [comment]
Agreed. Pull requests welcome!

**Comment by RonnyPfannschmidt** [comment]
I rnded up dropping this package and writing a small self contained rate limiter

**Comment by jmcarp** [comment]
:+1:
